# Generated by Django 5.0.3 on 2024-03-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.IntegerField(help_text='Square feet')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking_slots', models.IntegerField(default=1)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
